[package]
name = "rsfts"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.31", features = ["serialize"] }
flate2 = "1.0"
rust-stemmers = "1.2"
clap = { version = "4.5", features = ["derive"] }
